### ISSUE TITLE
call_indirect to a null table entry in Browser Environment

### ISSUE THREAD

**Issue by jotoh98** [geegaz/GMTK_Jam_2020#3]
If I try to start the game in browser, I get this message:
```
[Error] call_indirect to a null table entry (evaluating 'Module["asm"]["Gi"].apply(null,arguments)')
	displayFailureNotice (index.html:248)
	promiseReactionJob
```
I dont know if its supposed to work in the browser environment. Im using Safari Version 13.1.2 (15609.3.5.1.3) on macOS Catalina 10.15.6.

**Comment by geegaz** [comment]
Thank you for reporting, I'll try to see what could be causing this issue.
In the meantime, I'd recommend using the standalone macOS version instead.

**Comment by geegaz** [comment]
After further investigation, it seems to happend with Godot web games on Safari. I can't do anything about it since it's an engine/browser problem, the solution is to use another browser or the standalone version.

**Comment by geegaz** [comment]
Seems to be fixed by https://github.com/godotengine/godot/pull/39538, closing now

**Comment by geegaz** [comment]
Seems to be fixed by https://github.com/godotengine/godot/pull/39538, closing issue
